import os
from PIL import Image, ImageOps

# Source image generated by Antigravity
source_path = r"C:\Users\brunn\.gemini\antigravity\brain\fe728f04-1caa-4a55-ac53-8167d16be890\switch_volume_logo_1781860096626.png"
assets_dir = r"c:\Workspace\ChangeAudioDeviceCommandPalleteExtension\ChangeAudioDeviceCommandPalleteExtension\ChangeAudioDeviceCommandPalleteExtension\Assets"

# Ensure assets directory exists
os.makedirs(assets_dir, exist_ok=True)

# Open the source image
img = Image.open(source_path)

# Definition of targets: (filename, width, height, fit_mode)
# fit_mode: 'resize' for direct resizing, 'pad' to fit inside with padding
targets = [
    ("StoreLogo.png", 50, 50, "resize"),
    ("Square150x150Logo.scale-200.png", 300, 300, "resize"),
    ("Square44x44Logo.scale-200.png", 88, 88, "resize"),
    ("Square44x44Logo.targetsize-24_altform-unplated.png", 24, 24, "resize"),
    ("LockScreenLogo.scale-200.png", 48, 48, "resize"),
    ("Wide310x150Logo.scale-200.png", 620, 300, "pad"),
    ("SplashScreen.scale-200.png", 1240, 600, "pad"),
]

for filename, w, h, mode in targets:
    dest_path = os.path.join(assets_dir, filename)
    print(f"Generating {filename} ({w}x{h}) using {mode}...")
    
    if mode == "resize":
        # Direct resize with high quality resampling
        resized = img.resize((w, h), Image.Resampling.LANCZOS)
        resized.save(dest_path, "PNG")
    elif mode == "pad":
        # Create a new background canvas (transparent for wide logo, dark for splash screen)
        # Using a dark theme color matching the logo background (e.g., #111115 or transparent)
        is_splash = "SplashScreen" in filename
        bg_color = (17, 17, 21, 255) if is_splash else (0, 0, 0, 0)
        
        canvas = Image.new("RGBA", (w, h), bg_color)
        
        # Determine the size of the logo to fit on the canvas
        logo_h = int(h * 0.6)  # logo takes 60% of the height
        logo_w = logo_h
        
        resized_logo = img.resize((logo_w, logo_h), Image.Resampling.LANCZOS)
        
        # Center the logo on the canvas
        offset_x = (w - logo_w) // 2
        offset_y = (h - logo_h) // 2
        
        canvas.paste(resized_logo, (offset_x, offset_y), resized_logo if resized_logo.mode == "RGBA" else None)
        canvas.save(dest_path, "PNG")

print("All assets generated successfully!")
